name: 'VSCode Build'
  
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - feature/*
      - hotfix/*
    paths:
      - 'vscode/**'
      - 'shared/**'
      - 'util/**'
      - 'build/**'
      - 'agent/**'
      - '.github/workflows/vscode-build.yml'
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
      - master
    paths:
      - 'vscode/**'
      - 'shared/**'
      - 'util/**'
      - 'build/**'
      - 'agent/**'
      - '.github/workflows/vscode-build.yml'

jobs:
  VSCode:     
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hrishikesh-kadam/setup-lcov@v1

    - name: Read package.json
      id: package_version  
      uses: zvonimirsun/read-package-version-actions@v2
      with: 
        path: ./vscode
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.5.0
        cache: 'npm'

    - name: NPM Install
      run: |
        cd ./shared/util
        npm ci --ignore-scripts
        cd ../build
        npm ci --ignore-scripts
        cd ../ui
        npm ci --ignore-scripts
        cd ../agent
        npm ci --ignore-scripts
        cd ../../vscode
        npm ci --ignore-scripts
        
    - name: Compile & Verify
      run: |
        cd ./shared/ui
        npm run verify:compile  
        cd ../agent
        npm run verify:compile
        cd ../../vscode
        npm run verify:compile

    - name: Run Tests
      id: test_run
      run: |
        cd ./shared/build
        npm run test:ci
        cd ../util
        npm run test:ci
        cd ../agent
        npm run test:ci:unit
        cd ../ui
        npm run test:ci
        cd ../../vscode
        npm run test:ci

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: steps.test_run.conclusion == 'success' || steps.test_run.conclusion == 'failure'
      with:
        name: Test Reports
        path: '**/junit.xml'
        reporter: jest-junit

    - name: VSCode Code Coverage Report
      uses: zgosalvez/github-actions-report-lcov@v3
      if: steps.test_run.conclusion == 'success'
      with:
        coverage-files: coverage/lcov.info
        minimum-coverage: 0
        working-directory: vscode
        artifact-name: vscode-code-coverage-report
        update-comment: true

    # - name: Agent Code Coverage Report
    #   uses: zgosalvez/github-actions-report-lcov@v3
    #   if: steps.test_run.conclusion == 'success'
    #   with:
    #     coverage-files: './coverage/lcov.info'
    #     minimum-coverage: 0
    #     working-directory: './shared/agent'
    #     artifact-name: vagent-code-coverage-report
    #     update-comment: true

    - name: Build Assets
      run: |
        cd ./shared/agent
        npm run build
        cd ../../vscode
        npm run build
        
    - name: Pack It Up
      run: |
        cd ./vscode
        npm run pack
        mv codestream-*.vsix codestream-${{ steps.package_version.outputs.version }}-${{ github.run_number }}.vsix

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: vscode-codestream-${{ steps.package_version.outputs.version }}-${{ github.run_number }}
        path: ./vscode/codestream-*.vsix
