name: 'VSCode Build'
  
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - feature/*
      - hotfix/*
    paths:
      - 'vscode/**'
      - 'shared/**'
      - 'util/**'
      - 'build/**'
      - 'agent/**'
      - '.github/workflows/vscode-build.yml'
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
      - master
    paths:
      - 'vscode/**'
      - 'shared/**'
      - 'util/**'
      - 'build/**'
      - 'agent/**'
      - '.github/workflows/vscode-build.yml'

jobs:
  VSCode:     
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Read package.json
      id: package_version  
      uses: zvonimirsun/read-package-version-actions@v2
      with: 
        path: ./vscode
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.5.0

    - name: NPM Install
      run: |
        cd ./shared/util
        npm install --no-save --ignore-scripts
        cd ../build
        npm install --no-save --ignore-scripts
        cd ../ui
        npm install --no-save --ignore-scripts
        cd ../agent
        npm install --no-save --ignore-scripts
        cd ../../vscode
        npm install --no-save --ignore-scripts
        
    - name: Compile & Verify
      run: |
        cd ./shared/ui
        npm run verify:compile  
        cd ../agent
        npm run verify:compile
        cd ../../vscode
        npm run verify:compile

    - name: Run Tests
      run: |
        cd ./shared/build
        npm run test
        cd ../util
        npm run test
        cd ../agent
        npm run test:ci:unit
        cd ../ui
        npm run test:ci
        cd ../../vscode
        npm run vscode:test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: JEST Tests
        path: '**/junit.xml'
        reporter: jest-junit

    - name: Build Assets
      run: |
        cd ./shared/agent
        npm run build
        cd ../../vscode
        npm run build
        
    - name: Pack It Up
      run: |
        cd ./vscode
        npm run pack
        mv codestream-*.vsix codestream-${{ steps.package_version.outputs.version }}-${{ github.run_number }}.vsix

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: vscode-codestream-${{ steps.package_version.outputs.version }}-${{ github.run_number }}
        path: ./vscode/codestream-*.vsix
