name: 'VSCode Build'
  
on:
  workflow_dispatch:
 
jobs:
  VSCode-Build:     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 18.5.0

    - name: NPM Install
      shell: pwsh
      run: |
        cd ./vscode
        npm install --no-save
        
    - name: Compile & Verify
      run: |
        cd ./vscode
        npm run verify:compile
        cd ../shared/agent
        npm run verify:compile
        cd ../ui
        npm run verify:compile

# need NPM scripts that don't use pushd/popd
#    - name: Test VSCode
#      run: |
#        cd ./vscode
#        npm run vscode:test
#        cd ../shared/agent
#        npm run test-unit
#        cd ../ui
#        npm run test:ci

    - name: Build Agent
      run: |
        cd ./shared/agent
        npm run build

    - name: Build VSCode
      run: |
        cd ./vscode
        npm run build        
        
    - name: Pack It Up
      run: |
        cd ./vscode
        npm run pack

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ./vscode/codestream-*.vsix
    
